In [2]:
import numpy as np
import pandas as pd

## NP array creation

### Creating a NP arrays

In [3]:
# From a list
np.array([(1.5,2,3), (4,5,6)])

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [4]:
# creating an array from 0 to 14
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# creating an array of 3 rows and 5 columns
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
# knowing the dimension of an array
a = np.array([[1,2],[1,2]])

a.shape

(2, 2)

### Indexing and slicing

In [9]:
# 1D array
a_np=np.array([1.5,2,3,4,5,6])

# indexing 1-dimensional array
a_np[1]

2.0

In [11]:
# indexing a 2-dimensional array
x = np.arange(10)
x.shape = (2,5)

print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
print(x[0,1])

1


In [14]:
# getting the first row
print(x[0,:])

[0 1 2 3 4]


In [15]:
# getting the first column
print(x[:,0])

[0 5]


### Creating a dataframe from a Numpy array

In [7]:
data = np.array([['Col1','Col2','Col3'],['Row1',1,2],['Row2',3,4]])
pd.DataFrame(data=data)

0     1     2
0  Col1  Col2  Col3
1  Row1     1     2
2  Row2     3     4

In [17]:
# Now, if we want to add the column names:
pd.DataFrame(data=data,columns=['A','B','C'])

A     B     C
0  Col1  Col2  Col3
1  Row1     1     2
2  Row2     3     4

## Functions

numpy.random.randn= Return a sample (or samples) from the “standard normal” distribution.

In [4]:
np.random.randn(10)

array([ 0.57524796, -0.90596758, -2.45666346,  0.15857955, -2.44603902,
       -0.08742281, -0.11018107, -0.51650214, -0.02794454, -0.64150039])

np.column_stack= Stack different np arrays by columns

In [19]:
x1 = np.random.randn(10)
x2 = 4*np.random.randn(10)
x3 = 0.5*np.random.randn(10)

np.column_stack([x1, x2, x3])

array([[-0.14420257,  1.83936525,  0.55053714],
       [ 0.04297711,  5.26042905,  0.07472966],
       [-1.27912205,  3.09480268,  0.64416636],
       [-0.45224856,  2.61380648, -0.07034314],
       [-1.02468742,  1.75614364, -0.11954021],
       [ 1.85715856, -1.2324341 ,  0.53565721],
       [ 0.32937378,  1.73218913,  0.16899434],
       [-1.30607295, -0.16736164,  0.21618845],
       [ 1.11899122,  1.20899843,  0.11812464],
       [ 0.31619987,  6.14905578, -0.41107252]])

Standard deviation on a an array

In [20]:
np.std(x1)

0.97465103191895186

## Reading and saving to a file
The recommended way which is platform independt will be using the `load` and `save` functions:

In [2]:
import numpy as np

# an array example
X=np.array([(1.5,2,3), (4,5,6)])

In [3]:
fname='test'
np.save(fname, X)

In [4]:
np.load(fname+".npy")

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])